# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-05 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupname', models.CharField(max_length=32, verbose_name='\u7ec4\u540d\u5b57')),
            ],
        ),
        migrations.CreateModel(
            name='GroupPerssion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.IntegerField(verbose_name='\u7ec4ID')),
                ('perssion_id', models.IntegerField(verbose_name='\u6743\u9650ID')),
            ],
        ),
        migrations.CreateModel(
            name='PerssionDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obj_id', models.IntegerField(verbose_name='\u64cd\u4f5c\u5bf9\u8c61ID')),
                ('opera_name', models.CharField(max_length=32, verbose_name='\u64cd\u4f5c\u7c7b\u522b')),
                ('description', models.CharField(max_length=128, verbose_name='\u8be6\u60c5\u63cf\u8ff0')),
            ],
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='\u7528\u6237ID')),
                ('group_id', models.IntegerField(verbose_name='\u7ec4ID')),
            ],
        ),
        migrations.CreateModel(
            name='UserManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='\u7528\u6237\u540d')),
                ('password', models.CharField(max_length=128, verbose_name='\u7528\u6237\u5bc6\u7801')),
                ('email', models.EmailField(max_length=254, verbose_name='\u7528\u6237\u90ae\u7bb1')),
                ('phone', models.CharField(max_length=32, verbose_name='\u7528\u6237\u624b\u673a\u53f7\u7801')),
                ('photo', models.ImageField(upload_to='', verbose_name='\u7528\u6237\u56fe\u7247')),
            ],
        ),
        migrations.CreateModel(
            name='UserPerssion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='\u7528\u6237ID')),
                ('perssion_id', models.IntegerField(verbose_name='\u6743\u9650ID')),
            ],
        ),
    ]
