# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-05 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=64, verbose_name='\u4e3b\u673a\u540d\u5b57')),
                ('ip', models.GenericIPAddressField(verbose_name='IP\u5730\u5740')),
                ('mac', models.CharField(max_length=64, verbose_name='\u673a\u5668Mac\u5730\u5740')),
                ('sys_type', models.CharField(max_length=32, verbose_name='\u64cd\u4f5c\u7cfb\u7edf\u7c7b\u578b')),
                ('sys_version', models.CharField(max_length=32, verbose_name='\u64cd\u4f5c\u7cfb\u7edf\u7248\u672c')),
                ('cpu_count', models.IntegerField(verbose_name='cpu\u4e2a\u6570')),
                ('disk', models.CharField(max_length=32, verbose_name='\u786c\u76d8\u5927\u5c0f')),
                ('memory', models.CharField(max_length=32, verbose_name='\u5185\u5b58\u5927\u5c0f')),
            ],
        ),
    ]
