# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-20 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CmdbWeb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(verbose_name='\u670d\u52a1\u5668\u5730\u5740')),
                ('username', models.CharField(max_length=32, verbose_name='\u767b\u5f55\u7528\u6237\u540d')),
                ('password', models.CharField(max_length=64, verbose_name='\u767b\u5f55\u5bc6\u7801')),
                ('port', models.IntegerField(max_length=5, verbose_name='\u767b\u5f55\u7aef\u53e3')),
            ],
        ),
        migrations.AlterField(
            model_name='equipmentdetail',
            name='cpu_count',
            field=models.CharField(max_length=4, verbose_name='cpu\u4e2a\u6570'),
        ),
    ]
