# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-20 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CmdbWeb', '0002_auto_20180320_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentdetail',
            name='cpu_count',
            field=models.CharField(max_length=8, verbose_name='cpu\u4e2a\u6570'),
        ),
    ]
